print("Let's make a Mad Lib!")
noun= input("Enter a noun")
noun_one= input("Enter another noun")
verb= input("Enter a verb")
verb_one= input("Enter another verb")
adjective= input("Enter an adjective")
verb_two= input("Enter a different verb")
noun_three= input("Enter a different noun")
adjective_two= input("Enter another adjective")

print("Once upon a time there lived a " + noun + " in a " + noun_one)
print(noun + verb + " to the zoo to " + verb_one + " milk from a hippo")
print("The hippo was extremely " + adjective + " and decided to " + verb_two + " over the fence")
print(noun_three + " found the hippo, took the milk back from " + noun + " ,and made a " + adjective_two + " latte")
print("The hippo " + verb + "and lived happily ever after with the " + noun_three)